title: FloodWatch
description: A Flood Analysis and Prediction Application

url: https://floodwatch-org.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: floodwatch-org
  # twitter: -
  # facebook: -
  email: todo@gmail.com
  # linkedin: -

google_analytics: "UA-58263416-1"

disqus:
    shortname: floodwatch-org
